# Generated by Django 5.1.6 on 2025-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="freshers",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="Yes", max_length=50
            ),
        ),
    ]
