# Generated by Django 5.1.6 on 2025-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0002_application_freshers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="freshers",
            field=models.CharField(max_length=255),
        ),
    ]
