# Generated by Django 5.1.6 on 2025-04-09 18:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0003_alter_application_freshers"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="application",
            name="certificates",
        ),
        migrations.RemoveField(
            model_name="application",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="application",
            name="github",
        ),
        migrations.RemoveField(
            model_name="application",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="application",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="application",
            name="resume",
        ),
        migrations.AddField(
            model_name="application",
            name="applied_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 4, 9, 18, 8, 41, 83999, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="experience",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="application",
            name="freshers",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="application",
            name="internship_role",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="application",
            name="position",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="application",
            name="preferred_technology",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="application",
            name="skills",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="internship",
            field=models.ForeignKey(
                default=22,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_auth.internshippost",
            ),
            preserve_default=False,
        ),
    ]
