# Generated by Django 6.0.2 on 2026-02-27 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_internshippost_reportedcontent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportedContent',
        ),
        migrations.RenameField(
            model_name='internshippost',
            old_name='date_posted',
            new_name='posted_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='company',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='internshippost',
            name='title',
        ),
        migrations.AddField(
            model_name='application',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='application',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='apply_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='internship_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='freshers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='internship_role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='preferred_technology',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Under Review', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
