# Generated by Django 6.0.2 on 2026-03-07 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_delete_reportedcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
