# Generated by Django 6.0.2 on 2026-03-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_user_profile_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='position',
        ),
    ]
