# Generated by Django 6.0.2 on 2026-03-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_question_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.CharField(choices=[('Python', 'Python'), ('Web', 'Web Development'), ('DS', 'Data Science'), ('AI', 'AI/ML')], default='Python', max_length=50),
        ),
    ]
