# Generated by Django 6.0.2 on 2026-03-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_question_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.application'),
        ),
    ]
