# Generated by Django 6.0.2 on 2026-03-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_testresult_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='application',
        ),
    ]
