# Generated by Django 6.0.2 on 2026-03-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_testresult_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_taken',
            field=models.BooleanField(default=False),
        ),
    ]
