# Generated by Django 6.0.2 on 2026-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_question_expected_output_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expected_output',
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
