# Generated by Django 6.0.2 on 2026-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_remove_question_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='coding_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='coding_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='mcq_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='mcq_total',
            field=models.IntegerField(default=0),
        ),
    ]
