# Generated by Django 6.0.2 on 2026-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_testresult_coding_score_testresult_coding_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='starter_code',
            new_name='starter_code_cpp',
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code_java',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code_python',
            field=models.TextField(blank=True, null=True),
        ),
    ]
