# Generated by Django 6.0.2 on 2026-03-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0017_rename_starter_code_question_starter_code_cpp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='starter_code_web',
            field=models.TextField(blank=True, null=True),
        ),
    ]
