# Generated by Django 6.0.2 on 2026-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0018_question_starter_code_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
