# Generated by Django 6.0.2 on 2026-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_testresult_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('company', 'Company')], default='student', max_length=20),
        ),
    ]
