# Generated by Django 6.0.2 on 2026-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
