# Generated by Django 6.0.2 on 2026-04-09 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0024_companyprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_auth.internshippost'),
        ),
        migrations.AddField(
            model_name='internshippost',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL),
        ),
    ]
